API_ID: 25554706 
API_HASH: 1c34975731321b6850d4ee02e71f5ce3
BOT_TOKEN: 6606961842:AAGCGXytO_u5QVIi9EZvZrWdKHfbFDlYqXk


MONGO_URL: ReuSNuqoSiX31Czo
REDIS_URI: 
REDIS_PORT:
REDIS_PASS:

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 
  - 5650988605

OWNER: 5650988605

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: disconnected11
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

